[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#F63366"
backgroundColor="#0E1117"
secondaryBackgroundColor="#31333F"
textColor="#FAFAFA"
font="sans serif"
